services:
  network-deploy-service:
    networks:
      - sbdb-network # put the microservices in the same network, for enable the communication with each other 
 
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m # define the memory allocation 
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      SPRING_PROFILES_ACTIVE: prd
