services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # check se rabbitmq está operante (conforme documentação)
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "artcorb/sbdb-configserver:0.0.1-SNAPSHOT"
    container_name: sbdb-configserver
    ports:
      - "8888:8888"
    # verifica se o rabbitmq está operante antes de subir
    depends_on:
      rabbit:
        condition: service_healthy
    # check se configserver está operante
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "artcorb/sbdb-ms-accounts:0.0.1-SNAPSHOT"
    container_name: sbdb-ms-accounts
    ports:
      - "8080:8080" # in/out ports for the microservice
    # verifica se configserver está operante antes de subir
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "artcorb/sbdb-ms-cards:0.0.1-SNAPSHOT"
    container_name: sbdb-ms-cards
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "artcorb/sbdb-ms-loans:0.0.1-SNAPSHOT"
    container_name: sbdb-ms-loans
    ports:
      - "8082:8082"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  sbdb-network:
    driver: "bridge" # create the network with the name "sbdb-network"
