services:
  sbdb-db-accounts:
    container_name: sbdb-db-accounts
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sbdb-db-accounts
    extends:
      file: common-config.yml
      service: microservice-db-config

  sbdb-db-loans:
    container_name: sbdb-db-loans
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: sbdb-db-loans
    extends:
      file: common-config.yml
      service: microservice-db-config

  sbdb-db-cards:
    container_name: sbdb-db-cards
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: sbdb-db-cards
    extends:
      file: common-config.yml
      service: microservice-db-config

networks:
  sbdb-network:
    driver: "bridge" # create the network with the name "sbdb-network"
